### ISSUE TITLE
viewMail

### ISSUE THREAD

**Issue by just1ngray** [just1ngray/CSCI2356_AutismNS#4]
I do not know how to change the window location and load the new page using scripts in the same function.

i.e.
function do() {
window.location = ...
$("#...").html("...")
}

Thus, the email.html page does not display anything yet.

**Comment by vbjeronimo** [comment]
Maybe you should write a different function, place it in an "onload" attribute in the "body" tag and write an if statement inside the function to load the page the way you want.

JavaScript:
function do() {
    window.location.href = ...;
}

function load() {
    if(condition1) {
        $("#...").html("...");
    } else if (condition2) {
        $("#...").html("...");
    }
}

HTML:
"body onload="load()" ... /body"

(I'm replacing the < and > for " " because the comment section sees it as HTML code).

**Comment by vbjeronimo** [comment]
I tried finding a solution to this issue but I think I need you to explain how some parts of the code work.

 Also, I think we could simplify the code a little bit so it will be easier to maintain when we have to deal with the server part of the project. Let me know what you think.
